### Les assiettes

On dispose d'un nombre de X assiettes pouvant etre empilées sur Y tas. En utilisant toutes les assiettes et en faisant en sorte qu'aucun tas n'ait le meme nombre d'assiette : Quel nombre maximum d'assiette peut comporter la pile la plus petite ?

In [19]:
def less_maxima(start, pile):
    if int(start) != start or int(pile) != pile:
        print("not int error")
        return
    if pile <= 0:
        print("pile need to be > 0")
        return
    minimum = pile * (pile - 1) / 2
    if start < minimum:
        print("start too low, no solution possible")
        return
    start -= minimum
    print(start // pile)
    
less_maxima(3, 3)

0.0


### 3^3 cube

Avec un ensemble de pieces 3D donnés, il faut réaliser un cube. Tester toutes les possibilitées éxistantes, c'est partit.
(faudra aussi penser a opti mdr)

In [73]:
import numpy as np

def row_exist(piece_row, value):
    for i in piece_row:
        if value in i:
            return 1
    return 0

def piece_compare(piece_map, cmpr):
    for i in range(3):
        for j in range(3):
            for k in range(3):
                if piece_map[i][j][k] != cmpr[i][j][k]:
                    print("not same")
                    return 0
    print("same")
    return 1

def replace_piece(piece, val_piece=1, p_map=None):
    if (p_map == None):
        p_map = np.zeros(np.shape(3,3,3))
    fix_pos = []
    min_down = 3
    min_left = 3
    min_front = 3
    for i in range(3):
        for j in range(3):
            for k in range(3):
                if p_map[i,j,k] == val_piece:
                    fix_pos.append((i,j,k))
                    if min_down > i:
                        min_down = i
                    if min_left > j:
                        min_left = j
                    if min_front > k:
                        min_front = k
    
    
    
    for j in range(2):
        if row_exist(piece_map[0], 1) == 0:
            piece_map = np.delete(piece_map, 0, 0)
            piece_map = np.append(piece_map, [[[0,0,0],[0,0,0],[0,0,0]]], axis=0)
    for j in range(2):
        if row_exist(piece_map[:,0], 1) == 0:
            piece_map = np.delete(piece_map, 0, 1)
            piece_map = np.append(piece_map, [[[0,0,0]],[[0,0,0]],[[0,0,0]]], axis=1)
    for j in range(2):
        if row_exist(piece_map[:,:,0], 1) == 0:
            piece_map = np.delete(piece_map, 0, 2)
            piece_map = np.append(piece_map, [[[0],[0],[0]],[[0],[0],[0]],[[0],[0],[0]]], axis=2)            
    return piece_map

def all_possibilities(piece_map):
    
    pass

#6 faces have to be seen in front, turning is clockwise
#up, down, right, left, front, back
#each turn can only go clockwise
#rotate code can be (u,r,d) which is equal to (b)
def rotate(piece, rotate_code):
    for i in rotate_code:
        if i == "r":
            piece = np.rot90(piece,  1, (0,1))
        if i == "l":
            piece = np.rot90(piece, -1, (0,1))
        if i == "b":
            piece = np.rot90(piece,  1, (0,2))
        if i == "f":
            piece = np.rot90(piece, -1, (0,2))
        if i == "d":
            piece = np.rot90(piece,  1, (1,2))
        if i == "u":
            piece = np.rot90(piece, -1, (1,2))

piece_T  = np.array([[[1,1,1],[0,1,0],[0,0,0]], [[0,0,0],[0,0,0],[0,0,0]], [[0,0,0],[0,0,0],[0,0,0]]])
piece_L  = np.array([[[1,1,1],[1,0,0],[0,0,0]], [[0,0,0],[0,0,0],[0,0,0]], [[0,0,0],[0,0,0],[0,0,0]]])
piece_Z  = np.array([[[1,1,0],[0,1,1],[0,0,0]], [[0,0,0],[0,0,0],[0,0,0]], [[0,0,0],[0,0,0],[0,0,0]]])
piece_tL = np.array([[[1,1,0],[0,1,0],[0,0,0]], [[0,0,0],[0,0,0],[0,0,0]], [[0,0,0],[0,0,0],[0,0,0]]])
piece_tt = np.array([[[1,1,0],[1,1,0],[0,0,0]], [[0,0,0],[0,1,0],[0,0,0]], [[0,0,1],[0,1,1],[0,0,1]]])


same
1
[[[1 1 1]
  [0 1 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [114]:
piece_test = np.array([[[1,1,0],[1,1,0],[0,0,0]], [[0,0,0],[0,1,0],[0,0,0]], [[0,0,1],[0,1,1],[0,0,1]]])

In [113]:
def check_adj(piece, value, i, j, k):
    total = 0
    if i > 0:
        total += (piece[i-1][j][k] == value)
    if i < len(piece) - 1:
        total += (piece[i+1][j][k] == value)
    if j > 0:
        total += (piece[i][j-1][k] == value)
    if j < len(piece) - 1:
        total += (piece[i][j+1][k] == value)
    if k > 0:
        total += (piece[i][j][k-1] == value)
    if k < len(piece) - 1:
        total += (piece[i][j][k+1] == value)
    return total

def check_is_real(piece):
    for i in range(2):
        for j in range(2):
            for k in range(2):
                if piece[i][j][k] == 0 and check_adj(piece, 0, i, j, k) == 0:
                    return 0
    return 1

def gen_piece():
    total = 0
    for i in range(8):
        for j in range(i+1, 8):
            for k in range(j+1, 8):
                piece = np.array([[[1,1],[1,1]], [[1,1],[1,1]]])
                piece[i//4, i//2%2, i%2] = 0
                piece[j//4, j//2%2, j%2] = 0
                piece[k//4, k//2%2, k%2] = 0
                if check_is_real(piece) == 1:
                    total += 1
                    print(piece, "\n-----")
    print(total)

#6 faces have to be seen in front, turning is clockwise
#up, down, right, left, front, back
#each turn can only go clockwise
#rotate code can be (u,r,d) which is equal to (b)
def rotate(piece, rotate_code):
    for i in rotate_code:
        if i == "r":
            piece = np.rot90(piece,  1, (0,1))
        if i == "l":
            piece = np.rot90(piece, -1, (0,1))
        if i == "b":
            piece = np.rot90(piece,  1, (0,2))
        if i == "f":
            piece = np.rot90(piece, -1, (0,2))
        if i == "d":
            piece = np.rot90(piece,  1, (1,2))
        if i == "u":
            piece = np.rot90(piece, -1, (1,2))
    print(piece)
            
piece = np.array([[[1,1],[1,1]], [[0,0],[0,1]]])
print(piece, "\n----")
rotate(piece, ("u","d"))

[[[1 1]
  [1 1]]

 [[0 0]
  [0 1]]] 
----
[[[1 1]
  [1 1]]

 [[0 0]
  [0 1]]]


In [81]:
piece = [[[1,1],[1,1]], [[1,1],[1,1]]]
print(piece[0, 1, 2])

TypeError: list indices must be integers or slices, not tuple