In [10]:
import numpy as np

def replace_piece(piece):
    for i in range(3):
        for j in range(3):
            if piece[i,j] == 1: #erase the old position
                piece[i,j] = 0
    for i in range(2):
        for j in range(2):
            piece[i,j] = 1 #write the good one
    print("Return :")
    print(piece)
    return piece

def rotate(piece):
    piece = np.rot90(piece, -1, (0,1)) #apply rotation
    return piece

def gen_piece(piece): #generate all 4 rototations and reposition it
    list_piece = []
    for j in range(4):
        list_piece.append(replace_piece(piece))
        piece = rotate(piece) #turn the piece by 90°
    return list_piece

piece = np.array([[1,1,0],[1,1,0],[0,0,0]])
list_piece = gen_piece(piece)
print("\nIn list_piece :")
for i in list_piece:
    print(i)

Return :
[[1 1 0]
 [1 1 0]
 [0 0 0]]
Return :
[[1 1 0]
 [1 1 0]
 [0 0 0]]
Return :
[[1 1 0]
 [1 1 0]
 [0 0 0]]
Return :
[[1 1 0]
 [1 1 0]
 [0 0 0]]

In list_piece :
[[0 1 1]
 [0 1 1]
 [0 0 0]]
[[0 0 0]
 [0 1 1]
 [0 1 1]]
[[0 0 0]
 [1 1 0]
 [1 1 0]]
[[1 1 0]
 [1 1 0]
 [0 0 0]]
