In [137]:
import numpy as np
import copy
import matplotlib.pyplot as plt

class Chessboard():
    def __init__(self, dim_x, dim_y, offset):
        self.dim_x = dim_x
        self.dim_y = dim_y
        self.queen = min(dim_x, dim_y)
        self.queen_pos = [0] * self.queen
        self.avail_col = [1] * dim_y
        self.avail_diag_slash = [1] * (dim_x + dim_y - 1)
        self.avail_diag_back = [1] * (dim_x + dim_y - 1)
        self.solution = 0
        self.lastpos = -1
        self.start = 0
        
        print("\noffset", offset)
        if offset == 0:
            for i in range(0,(self.queen+1)//2):
                self.queen_pos[i] = i*2
                self.avail_col[i*2] = 0
                self.avail_diag_slash[i+i*2] = 0
                self.avail_diag_back[i-(i*2)] = 0
                self.start += 1
            self.print_map()
        if offset == 1:
            for i in range(0,self.queen//2):
                self.queen_pos[i] = i*2+1
                self.avail_col[i*2+1] = 0
                self.avail_diag_slash[i+i*2+1] = 0
                self.avail_diag_back[i-(i*2+1)] = 0
                self.start += 1
            self.print_map()
        if offset == 2:
            for i in range(0,self.queen//2-1):
                self.queen_pos[i] = i*2+2
                self.avail_col[i*2+2] = 0
                self.avail_diag_slash[i+i*2+2] = 0
                self.avail_diag_back[i-(i*2+2)] = 0
                self.start += 1
            self.print_map()
        
        #print(self.dim_x, self.dim_y, self.queen, self.queen_pos, self.avail_col, self.avail_diag_slash, self.avail_diag_back)           
        
        self.step(self.avail_col, self.avail_diag_slash, self.avail_diag_back, self.start)
        if self.solution == 0:
            print("No solution")
        else:
            print("Solutions :", self.solution)
    
    def print_map(self, mapping=None):
        if mapping == None:
            mapping = self.put_queen_in_map()
        for i in mapping:
            res = "|"
            for j in i:
                if j == 0:
                    res += " "
                else:
                    res += "X"
            res += "|"
            print(res)
        print("-"*(self.queen+2))
        return mapping
    
    def put_queen_in_map(self, queen_pos=None):
        if queen_pos == None:
            queen_pos = self.queen_pos
        solution = np.zeros((self.dim_x, self.dim_y))
        for idx, i in enumerate(queen_pos):
            solution[idx, i] = 1
        return solution
    
    def update_avail(self, avail_array, index):
        avail_array[index] = 0
        return avail_array
    
    def check_pos(self, avail_col, avail_diag_slash, avail_diag_back, x, y):
        if avail_col[y] == 0:
            return 0
        if avail_diag_slash[x+y] == 0:
            return 0
        if avail_diag_back[x-y] == 0:
            return 0
        return 1

    def step(self, avail_col, avail_diag_slash, avail_diag_back, depth):
        if self.solution == -1:
            return
        if depth == self.queen:
            self.print_map()
            self.solution += 1
        else:
            for col in range(self.dim_y):
                if self.check_pos(avail_col, avail_diag_slash, avail_diag_back, depth, col) == 1:
                    self.queen_pos[depth] = col
                    self.step(self.update_avail(copy.copy(avail_col), col),
                        self.update_avail(copy.copy(avail_diag_slash), depth + col),
                        self.update_avail(copy.copy(avail_diag_back), depth - col),
                        depth + 1)

dim = 15
Chessboard(dim,dim,0)
Chessboard(dim,dim,1)
Chessboard(dim,dim,2)


offset 0
|X              |
|  X            |
|    X          |
|      X        |
|        X      |
|          X    |
|            X  |
|              X|
|X              |
|X              |
|X              |
|X              |
|X              |
|X              |
|X              |
-----------------
No solution

offset 1
| X             |
|   X           |
|     X         |
|       X       |
|         X     |
|           X   |
|             X |
|X              |
|X              |
|X              |
|X              |
|X              |
|X              |
|X              |
|X              |
-----------------
No solution

offset 2
|  X            |
|    X          |
|      X        |
|        X      |
|          X    |
|            X  |
|X              |
|X              |
|X              |
|X              |
|X              |
|X              |
|X              |
|X              |
|X              |
-----------------
|  X            |
|    X          |
|      X        |
|        X      |
|         

In [1]:
test = [0,1,2]
del test[1]
print(test)

[0, 2]


In [34]:
import numpy as np

class NewChessboard():
    def __init__(self, dim_x, dim_y, queen=None):
        if queen == None:
            queen = min(dim_x, dim_y)
        if queen > min(dim_x, dim_y):
            print("Too many queens, cannot find a solution")
            return None
        self.dim_x = dim_x
        self.dim_y = dim_y
        self.queen = queen
        self.queen_x_pos = [0] * queen
        self.queen_y_pos = [0] * queen
        self.amount_line = [0] * dim_x
        self.amount_col = [0] * dim_y
        self.amount_diag_slash = [0] * (dim_x + dim_y - 1)
        self.amount_diag_back = [0] * (dim_x + dim_y - 1)
        self.map = None #np.zeros((dim_x, dim_y))
        
        #self.make_first()

    def get_queen_pos(self, mapping):
        queen_pos = []
        for i in range(len(mapping)):
            for j in range(len(mapping)):
                if mapping[i][j] == 1:
                    queen_pos.append([i,j])
        return queen_pos
    
    def check_solution(self, queen_pos=None, mapping=None):
        if queen_pos == None:
            if mapping == None:
                queen_pos = self.queen_pos
            else:
                queen_pos = self.get_queen_pos(mapping)
        if len(queen_pos[0]) == 1:
            for idx, i in enumerate(queen_pos):
                
        else:
            
    
    def update_amount(self, x, y, value=1):
        self.amount_line[x] += value
        self.amount_col[y] += value
        self.amount_diag_slash[x+y] += value
        self.amount_diag_back[x-y] += value
        
    def sol__dim_not_mod_2_nor_3(self):
        solution = np.zeros((self.dim_x, self.dim_y))
        for i in range(0,self.dim_x//2+1):
            solution[i][i*2] = 1
        for i in range(self.dim_x//2,self.dim_x):
            solution[i][(i*2-self.dim_x)] = 1
        print(solution)
        return solution
    
    def sol__dim_not_

    def make__full_random(self):
        self.map = np.zeros((dim_x, dim_y))
        queen_placement = 0
        while queen_placement != self.queen:
            rdm_x = np.random.randint(0,dim_x)
            rdm_y = np.random.randint(0,dim_y)
            if (self.map[rdm_x][rdm_y] == 0):
                self.map[rdm_x][rdm_y] = 1
                self.update_amount(rdm_x, rdm_y)
                queen_placement += 1
        return self.map
            
    def make__1_line_random_col(self):
        self.map = np.zeros((dim_x, dim_y))
        for i in range(0,queen):
            rdm_y = np.random.randint(0,dim_y)
            self.map[i][rdm_y] = 1
            self.update_amount(i, rdm_y)
        return self.map
        
    def make__1_line_1_col(self):
        self.map = np.zeros((dim_x, dim_y))
        avail = [i for i in range(0,dim_y)]
        for i in range(0,queen):
            rdm_y = avail[np.random.randint(0,dim_y-i)]
            avail[rdm_y] = avail[dim_y-i]
            self.map[i][rdm_y] = 1
            self.update_amount(i, rdm_y)
        return self.map
        
    def make__best_pos_per_line(self):
        self.map = np.zeros((dim_x, dim_y))
        for i in range(0,queen):
            pass
    
    def make__best_pos_overall(self):
        pass
        
NewChessboard(11,11)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


In [146]:
import numpy as np

class EndSolution():
    def __init__(self, dim):
        self.dim = dim
        self.queen_pos = [] #saves x and y coordinate of each queen
        self.solution_map = np.zeros((dim, dim))
        
        #I found 5 different patterns to place queens depending of dimension
        
        if dim%2 != 0 and dim%3 != 0:     #  5 7    11  13      17  19      23  25
            self.sol__not_mod2_and_not_mod3()
        if dim%2 == 0 and (dim-2)%3 != 0: # 4 6   10  12      16  18      22  24
            self.sol__mod2_and_not_m2_mod3()
        if (dim-2)%6 == 0:                #     8         14          20          26
            self.sol__m2_mod6()
        if (dim-9)%12 == 0:               #      9                      21
            self.sol__m9_mod12()
        if (dim-3)%12 == 0:               #                 15                      27
            self.sol__m3_mod12()
        
        for i in self.queen_pos: #put queen in board
            self.solution_map[i[0], i[1]] = 1
        
        self.print_map()
        if self.check_map() == 1:
            print("OK", self.dim)
        else:
            print("ERROR MAP", self.dim)
        print()
        
    def print_map(self):
        for i in self.solution_map:
            res = "|"
            for j in i:
                res += " " if j == 0 else "X"
            res += "|"
            print(res)
        print("-"*(self.dim+2))
        
    def check_map(self):
        line = [0] * self.dim
        col = [0] * self.dim
        diag_slash = [0] * (self.dim*2-1)
        diag_back = [0] * (self.dim*2-1)
        for i in self.queen_pos:
            line[i[0]] += 1
            if line[i[0]] == 2:
                return 0
            col[i[1]] += 1
            if col[i[1]] == 2:
                return 0
            diag_slash[i[0]+i[1]] += 1
            if diag_slash[i[0]+i[1]] == 2:
                return 0
            diag_back[i[0]-i[1]] += 1
            if diag_back[i[0]-i[1]] == 2:
                return 0
        return 1
    
    #putting queens like stairs means that queen placement follows this pattern :
    # +1,+1,+1 for x and +2,+2,+2 for y
    
    #put queens like stairs starting at 0,0
    def sol__not_mod2_and_not_mod3(self):
        for i in range(0,self.dim):
            self.queen_pos.append([i,(i*2)%(self.dim)])
    
    #put queens like stairs starting at 0,1
    def sol__mod2_and_not_m2_mod3(self):
        for i in range(0,self.dim):
            self.queen_pos.append([i,(i*2+1)%(self.dim+1)])
    
    #put half queens like stairs starting at 0,1
    #put 3 queens at specific location
    #put the rest like stairs starting at queen//2+2,6
    def sol__m2_mod6(self):
        for i in range(0,self.dim//2):
            self.queen_pos.append([i,(i*2+1)%(self.dim+1)])
        self.queen_pos.append([self.dim//2+1,0])
        self.queen_pos.append([self.dim//2,2])
        self.queen_pos.append([self.dim-1,4])
        for i in range(self.dim//2+3, self.dim):
            self.queen_pos.append([i-1,(i*2+1)%(self.dim+1)])
        return 1
    
    #put half queens minus 1 like stairs starting at 0,2
    #put two queens at specific location
    #put the rest with this pattern : -1,+3,-1,+3,-1 for x and +2,+2,+2 for y starting at queen//2+1,2
    def sol__m9_mod12(self):
        for i in range(0,self.dim//2-1):
            self.queen_pos.append([i,i*2+2])
        self.queen_pos.append([self.dim//2-1,0])
        self.queen_pos.append([self.dim-1,self.dim-1])
        for i in range(0, self.dim//2):
            self.queen_pos.append([(i-(i%2)+(i-1)%2)+self.dim//2,i*2+1])
        return 1
    
    #put half queens like stairs starting at 0,2
    #put one queen at specific location
    #put the rest with this pattern : -1,+3,-1,+3,-1 for x and +2,+2,+2 for y starting at queen//2+1,2
    def sol__m3_mod12(self):
        for i in range(0,self.dim//2):
            self.queen_pos.append([i,i*2+2])
        self.queen_pos.append([self.dim-2,0])
        for i in range(0, self.dim//2):
            self.queen_pos.append([(i-(i%2)+(i-1)%2)+self.dim//2,i*2+1])
        return 1

for i in range(4,100):
    EndSolution(i)

| X  |
|   X|
|X   |
|  X |
------
OK 4

|X    |
|  X  |
|    X|
| X   |
|   X |
-------
OK 5

| X    |
|   X  |
|     X|
|X     |
|  X   |
|    X |
--------
OK 6

|X      |
|  X    |
|    X  |
|      X|
| X     |
|   X   |
|     X |
---------
OK 7

| X      |
|   X    |
|     X  |
|       X|
|  X     |
|X       |
|      X |
|    X   |
----------
OK 8

|  X      |
|    X    |
|      X  |
|X        |
|   X     |
| X       |
|       X |
|     X   |
|        X|
-----------
OK 9

| X        |
|   X      |
|     X    |
|       X  |
|         X|
|X         |
|  X       |
|    X     |
|      X   |
|        X |
------------
OK 10

|X          |
|  X        |
|    X      |
|      X    |
|        X  |
|          X|
| X         |
|   X       |
|     X     |
|       X   |
|         X |
-------------
OK 11

| X          |
|   X        |
|     X      |
|       X    |
|         X  |
|           X|
|X           |
|  X         |
|    X       |
|      X     |
|        X   |
|          X |
--------------

In [26]:
|  X                        |
|    X                      |
|      X                    |
|        X                  |
|          X                |
|            X              |
|              X            |
|                X          |
|                  X        |
|                    X      |
|                      X    |
|                        X  |
|                          X|
|   X                       |
| X                         |
|       X                   |
|     X                     |
|           X               |
|         X                 |
|               X           |
|             X             |
|                   X       |
|                 X         |
|                       X   |
|                     X     |
|X                          |
|                         X |


SyntaxError: invalid syntax (<ipython-input-26-302bc8ff07eb>, line 1)

In [76]:
3,2,5,4,7,6

for i in range(0,5):
    print(i-(i%2)+(i-1)%2)

1
0
3
2
5
