In [18]:
import numpy as np

"""
In order to definitely end this i'll make the best formula i've ever done (actually not but lol)

We define "id" as the piece_id which correspond to a unique piece shape.
It means you can have several piece with the same id. All piece with T shape will have the same id.

We define "val" as the piece_value which correspond to a unique piece.
You cannot have two pieces with same value.

There is two interaction that need to be checked, interact by id and by value.
That can create two matrix, one for each.

So you can split the formula in two part with one single condition piece1_id == piece2_id

For each position in space in need to find a array that will store each interaction


rdm lol =-=-=-=-=
total_interaction = (shape[0]-1)*shape[1]*shape[2] + shape[0]*(shape[1]-1)*shape[2] + shape[0]*shape[1]*(shape[2]-1)
                  = (x-1)*y*z + x*(y-1)*z + x*y*(z-1)
                  = xyz-yz + xyz-xz + xyz-xy
                  = 3*xyz - xy - xz - yz
"""
def total_itrc(shape):
    return 3*shape[0]*shape[1]*shape[2] - shape[0]*shape[1] - shape[0]*shape[2] - shape[1]*shape[2]

In [59]:
p = [0,1,2,3,5,7,11,13]
sum_list = [0,1,3,6,10,15,21,28]

def rotsym_3D(p_map, p_map_id, p_map_val, cmpr=None):
    total = 0
    len0 = len(p_map) #replace with self.shape
    len1 = len(p_map[0])
    len2 = len(p_map[0][0])
    for i in range(len0):
        for j in range(len1):
            for k in range(len2):
                if i > 0 and p_map[i][j][k] != p_map[i-1][j][k]:
                    total += p[p_map_id[i][j][k]+1]*p[p_map_id[i-1][j][k]+1]
                
                if j > 0 and p_map[i][j][k] != p_map[i][j-1][k]:
                    total += p[p_map_id[i][j][k]+1]*p[p_map_id[i][j-1][k]+1]
                
                if k > 0 and p_map[i][j][k] != p_map[i][j][k-1]:
                    total += p[p_map_id[i][j][k]+1]*p[p_map_id[i][j][k-1]+1]
    if cmpr == None:
        cmpr = total
    if total != cmpr:
        return total
    
    interaction = np.zeros((2,4,4))
    for i in range(len0):
        for j in range(len1):
            for k in range(len2):
                if i > 0:
                    interaction[p_map_id[i][j][k]-1, p_map[i][j][k], p_map[i-1][j][k]] = 1
                
                if j > 0:
                    interaction[p_map_id[i][j][k]-1, p_map[i][j][k], p_map[i][j-1][k]] = 1
                
                if k > 0:
                    interaction[p_map_id[i][j][k]-1, p_map[i][j][k], p_map[i][j][k-1]] = 1
    
    print(interaction)
    #total2 = 1
    #for i in range(len(interaction)):
    #    tmp = 1
    #    for j in range(len(interaction[0])):
    #        for k in range(j+1,len(interaction[0][0])):
    #            tmp += 
    #    total2 *= tmp
    return total

In [60]:
cube_ref     = [[[1,1],[2,2]],[[1,3],[2,4]]]
cube_ref_id  = [[[1,1],[1,1]],[[1,2],[1,2]]]
cube_ref_val = [[[0,0],[1,1]],[[0,0],[1,1]]]
cube_cmpr = []
cube_cmpr_id = []
cube_cmpr_val = []
torf = []

cube_cmpr.append([[[1,1],[2,2]],[[1,3],[4,2]]])
cube_cmpr_id.append( [[[1,1],[1,1]],[[1,2],[2,1]]])
cube_cmpr_val.append([[[0,0],[1,1]],[[0,0],[1,1]]])

cube_cmpr.append(    [[[1,1],[4,2]],[[1,3],[2,2]]])
cube_cmpr_id.append( [[[1,1],[2,1]],[[1,2],[1,1]]])
cube_cmpr_val.append([[[0,0],[1,1]],[[0,0],[1,1]]])

cube_cmpr.append(    [[[1,1],[4,2]],[[1,2],[3,2]]])
cube_cmpr_id.append( [[[1,1],[2,1]],[[1,1],[2,1]]])
cube_cmpr_val.append([[[0,0],[1,1]],[[0,1],[0,1]]])

print(rotsym_3D(cube_ref, cube_ref_id, cube_ref_val))
for i,j,k in zip(cube_cmpr, cube_cmpr_id, cube_cmpr_val):
    print()
    print()
    print(rotsym_3D(i, j, k))

[[[ 1.  0.  0.  0.]
  [ 1.  1.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 1.  0.  0.  0.]
  [ 1.  1.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]
45


[[[ 1.  0.  0.  0.]
  [ 1.  1.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 1.  0.  0.  0.]
  [ 1.  1.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]
44


[[[ 1.  0.  0.  0.]
  [ 1.  1.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 1.  0.  0.  0.]
  [ 1.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]
44


[[[ 1.  0.  0.  0.]
  [ 1.  1.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 1.  1.  0.  0.]
  [ 1.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]
45


In [54]:
cube_ref     = [[[1,1],[2,2]],[[3,3],[4,4]]]
cube_ref_id  = [[[1,1],[1,1]],[[1,1],[1,1]]]
cube_ref_val = [[[0,0],[1,1]],[[2,2],[3,3]]]
cube_cmpr = []
cube_cmpr_id = []
cube_cmpr_val = []
torf = []

cube_cmpr.append(    [[[1,2],[1,2]],[[3,4],[3,4]]])
cube_cmpr_id.append( [[[1,1],[1,1]],[[1,1],[1,1]]])
cube_cmpr_val.append([[[0,1],[0,1]],[[2,3],[2,3]]])

cube_cmpr.append(    [[[1,2],[1,2]],[[3,3],[4,4]]])
cube_cmpr_id.append( [[[1,1],[1,1]],[[1,1],[1,1]]])
cube_cmpr_val.append([[[0,1],[0,1]],[[2,2],[3,3]]])

cube_cmpr.append(    [[[2,1],[2,1]],[[3,3],[4,4]]])
cube_cmpr_id.append( [[[1,1],[1,1]],[[1,1],[1,1]]])
cube_cmpr_val.append([[[1,0],[1,0]],[[2,2],[3,3]]])

rotsym_3D(cube_ref, cube_ref_id, cube_ref_val)
for i,j,k in zip(cube_cmpr, cube_cmpr_id, cube_cmpr_val):
    rotsym_3D(i, j, k)

[[[ 1.  0.  0.  0.]
  [ 1.  1.  0.  0.]
  [ 1.  0.  1.  0.]
  [ 0.  1.  1.  1.]]]
[[[ 1.  0.  0.  0.]
  [ 1.  1.  0.  0.]
  [ 1.  0.  1.  0.]
  [ 0.  1.  1.  1.]]]
[[[ 1.  0.  0.  0.]
  [ 1.  1.  0.  0.]
  [ 1.  1.  1.  0.]
  [ 1.  1.  1.  1.]]]
[[[ 1.  1.  0.  0.]
  [ 0.  1.  0.  0.]
  [ 1.  1.  1.  0.]
  [ 1.  1.  1.  1.]]]
